# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.display = QtWidgets.QLineEdit(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(10, 20, 330, 40))
        font = QtGui.QFont()
        font.setFamily("SWRomnt")
        self.display.setFont(font)
        self.display.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.display.setObjectName("display")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 331, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Btn_sol = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_sol.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_sol.setFont(font)
        self.Btn_sol.setObjectName("Btn_sol")
        self.gridLayout.addWidget(self.Btn_sol, 0, 0, 1, 1)
        self.Btn_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_7.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_7.setFont(font)
        self.Btn_7.setObjectName("Btn_7")
        self.gridLayout.addWidget(self.Btn_7, 1, 0, 1, 1)
        self.Btn_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_8.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_8.setFont(font)
        self.Btn_8.setObjectName("Btn_8")
        self.gridLayout.addWidget(self.Btn_8, 1, 1, 1, 1)
        self.Btn_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_1.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_1.setFont(font)
        self.Btn_1.setObjectName("Btn_1")
        self.gridLayout.addWidget(self.Btn_1, 3, 0, 1, 1)
        self.Btn_bolme = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_bolme.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_bolme.setFont(font)
        self.Btn_bolme.setObjectName("Btn_bolme")
        self.gridLayout.addWidget(self.Btn_bolme, 0, 3, 1, 1)
        self.Btn_carpma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_carpma.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_carpma.setFont(font)
        self.Btn_carpma.setObjectName("Btn_carpma")
        self.gridLayout.addWidget(self.Btn_carpma, 1, 3, 1, 1)
        self.Btn_yuzde = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_yuzde.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_yuzde.setFont(font)
        self.Btn_yuzde.setObjectName("Btn_yuzde")
        self.gridLayout.addWidget(self.Btn_yuzde, 0, 2, 1, 1)
        self.Btn_sag = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_sag.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_sag.setFont(font)
        self.Btn_sag.setObjectName("Btn_sag")
        self.gridLayout.addWidget(self.Btn_sag, 0, 1, 1, 1)
        self.Btn_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_4.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_4.setFont(font)
        self.Btn_4.setObjectName("Btn_4")
        self.gridLayout.addWidget(self.Btn_4, 2, 0, 1, 1)
        self.Btn_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_9.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_9.setFont(font)
        self.Btn_9.setObjectName("Btn_9")
        self.gridLayout.addWidget(self.Btn_9, 1, 2, 1, 1)
        self.Btn_c = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_c.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_c.setFont(font)
        self.Btn_c.setObjectName("Btn_c")
        self.gridLayout.addWidget(self.Btn_c, 4, 0, 1, 1)
        self.Btn_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_5.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_5.setFont(font)
        self.Btn_5.setObjectName("Btn_5")
        self.gridLayout.addWidget(self.Btn_5, 2, 1, 1, 1)
        self.Btn_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_2.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_2.setFont(font)
        self.Btn_2.setObjectName("Btn_2")
        self.gridLayout.addWidget(self.Btn_2, 3, 1, 1, 1)
        self.Btn_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_0.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_0.setFont(font)
        self.Btn_0.setObjectName("Btn_0")
        self.gridLayout.addWidget(self.Btn_0, 4, 1, 1, 1)
        self.Btn_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_6.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_6.setFont(font)
        self.Btn_6.setObjectName("Btn_6")
        self.gridLayout.addWidget(self.Btn_6, 2, 2, 1, 1)
        self.Btn_toplama = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_toplama.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_toplama.setFont(font)
        self.Btn_toplama.setObjectName("Btn_toplama")
        self.gridLayout.addWidget(self.Btn_toplama, 2, 3, 1, 1)
        self.Btn_cikarma = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_cikarma.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_cikarma.setFont(font)
        self.Btn_cikarma.setObjectName("Btn_cikarma")
        self.gridLayout.addWidget(self.Btn_cikarma, 3, 3, 1, 1)
        self.Btn_esittir = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_esittir.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_esittir.setFont(font)
        self.Btn_esittir.setObjectName("Btn_esittir")
        self.gridLayout.addWidget(self.Btn_esittir, 4, 3, 1, 1)
        self.Btn_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_3.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_3.setFont(font)
        self.Btn_3.setObjectName("Btn_3")
        self.gridLayout.addWidget(self.Btn_3, 3, 2, 1, 1)
        self.Btn_00 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Btn_00.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.Btn_00.setFont(font)
        self.Btn_00.setObjectName("Btn_00")
        self.gridLayout.addWidget(self.Btn_00, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 380, 121, 20))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.Btn_1.clicked.connect(self.tus_1)
        self.Btn_2.clicked.connect(self.tus_2)
        self.Btn_3.clicked.connect(self.tus_3)
        self.Btn_4.clicked.connect(self.tus_4)
        self.Btn_5.clicked.connect(self.tus_5)
        self.Btn_6.clicked.connect(self.tus_6)
        self.Btn_7.clicked.connect(self.tus_7)
        self.Btn_8.clicked.connect(self.tus_8)
        self.Btn_9.clicked.connect(self.tus_9)
        self.Btn_0.clicked.connect(self.tus_0)
        self.Btn_00.clicked.connect(self.tus_00)
        self.Btn_sol.clicked.connect(self.parantez_ac)
        self.Btn_sag.clicked.connect(self.parantez_kapa)
        self.Btn_c.clicked.connect(self.silme)

        self.Btn_toplama.clicked.connect(self.topla)
        self.Btn_bolme.clicked.connect(self.bolme)
        self.Btn_cikarma.clicked.connect(self.cikar)
        self.Btn_carpma.clicked.connect(self.carpma)
        self.Btn_yuzde.clicked.connect(self.yuzde)

        self.Btn_esittir.clicked.connect(self.esitlik)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HesapMakinesi"))
        self.Btn_sol.setText(_translate("MainWindow", "("))
        self.Btn_7.setText(_translate("MainWindow", "7"))
        self.Btn_8.setText(_translate("MainWindow", "8"))
        self.Btn_1.setText(_translate("MainWindow", "1"))
        self.Btn_bolme.setText(_translate("MainWindow", "/"))
        self.Btn_carpma.setText(_translate("MainWindow", "*"))
        self.Btn_yuzde.setText(_translate("MainWindow", "%"))
        self.Btn_sag.setText(_translate("MainWindow", ")"))
        self.Btn_4.setText(_translate("MainWindow", "4"))
        self.Btn_9.setText(_translate("MainWindow", "9"))
        self.Btn_c.setText(_translate("MainWindow", "C"))
        self.Btn_5.setText(_translate("MainWindow", "5"))
        self.Btn_2.setText(_translate("MainWindow", "2"))
        self.Btn_0.setText(_translate("MainWindow", "0"))
        self.Btn_6.setText(_translate("MainWindow", "6"))
        self.Btn_toplama.setText(_translate("MainWindow", "+"))
        self.Btn_cikarma.setText(_translate("MainWindow", "-"))
        self.Btn_esittir.setText(_translate("MainWindow", "="))
        self.Btn_3.setText(_translate("MainWindow", "3"))
        self.Btn_00.setText(_translate("MainWindow", "00"))
        self.label.setText(_translate("MainWindow", "Made by C21stVillain"))
        


    def topla(self):
        icerik = self.display.text()
        icerik = icerik + "+"
        self.display.setText(icerik)

    def cikar(self):
        icerik = self.display.text()
        icerik = icerik + "-"
        self.display.setText(icerik)

    def bolme(self):
        icerik = self.display.text()
        icerik = icerik + "/"
        self.display.setText(icerik)

    def yuzde(self):
        icerik = self.display.text()
        icerik = icerik + "%"
        self.display.setText(icerik)

    def esitlik(self):
        icerik = self.display.text()
        if "%" in icerik:
            icerik = icerik.strip("%")
            cevap = int(icerik) / 100
        else:
            cevap = eval(icerik)
        self.display.setText(str(cevap))
        
    def silme(self):
        self.display.setText("")

    def carpma(self):
        icerik = self.display.text()
        icerik = icerik + "*"
        self.display.setText(icerik)

    def kontrol(self):
        pass

    def tus_1(self):
        icerik = self.display.text()
        icerik = icerik + "1"
        self.display.setText(icerik)


    def tus_2(self):
        icerik = self.display.text()
        icerik = icerik + "2"
        self.display.setText(icerik)

    def tus_3(self):
        icerik = self.display.text()
        icerik = icerik + "3"
        self.display.setText(icerik)

    def tus_4(self):
        icerik = self.display.text()
        icerik = icerik + "4"
        self.display.setText(icerik)

    def tus_5(self):
        icerik = self.display.text()
        icerik = icerik + "5"
        self.display.setText(icerik)

    def tus_6(self):
        icerik = self.display.text()
        icerik = icerik + "6"
        self.display.setText(icerik)

    def tus_7(self):
        icerik = self.display.text()
        icerik = icerik + "7"
        self.display.setText(icerik)

    def tus_8(self):
        icerik = self.display.text()
        icerik = icerik + "8"
        self.display.setText(icerik)


    def tus_9(self):
        icerik = self.display.text()
        icerik = icerik + "9"
        self.display.setText(icerik)


    def tus_0(self):
        icerik = self.display.text()
        icerik = icerik + "0"
        self.display.setText(icerik)

    def tus_00(self):
        icerik = self.display.text()
        icerik = icerik + "00"
        self.display.setText(icerik)

    def parantez_ac(self):
        icerik = self.display.text()
        icerik = icerik + "("
        self.display.setText(icerik)

    def parantez_kapa(self):
        icerik = self.display.text()
        icerik = icerik + ")"
        self.display.setText(icerik)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
